name: ci-algorithm

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: Lint and test algorithm
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - 3.8

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint algorithm
        run: black . --check

      - name: Test algorithm
        run: coverage run -m pytest

      - name: Print test coverage report
        run: coverage report -m
